# Generated by Django 3.2.6 on 2025-01-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_documento', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('organizacion', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=30)),
                ('Barrio', models.CharField(max_length=255)),
                ('grupo_poblacional', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
    ]
