# Generated by Django 3.2.6 on 2025-01-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255)),
                ('profesional', models.CharField(max_length=255)),
                ('lugar', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(null=True)),
            ],
        ),
    ]
