# Generated by Django 3.2.6 on 2025-01-13 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='forms.actividad'),
        ),
    ]
